# Generated by Django 4.0.3 on 2022-10-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilevo',
            name='has_sold',
            field=models.BooleanField(default=False),
        ),
    ]
