# Generated by Django 4.0.3 on 2022-10-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_serviceappointment_alter_technician_employee_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceappointment',
            name='time',
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
