# Generated by Django 4.0.3 on 2022-10-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_remove_serviceappointment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceappointment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
