# Generated by Django 4.0.3 on 2022-10-25 00:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_alter_serviceappointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceappointment',
            name='date',
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='scheduled_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='VIN',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='service_rest.technician'),
        ),
    ]
