# Generated by Django 4.0.3 on 2022-10-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_remove_serviceappointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceappointment',
            name='customer_name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='reason',
            field=models.CharField(max_length=50),
        ),
    ]
