# Generated by Django 4.0.3 on 2022-10-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_alter_serviceappointment_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceappointment',
            name='VIN',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='customer_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='reason',
            field=models.CharField(max_length=500),
        ),
    ]
