# Generated by Django 4.0.3 on 2022-10-25 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0007_alter_serviceappointment_vin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceappointment',
            name='VIN',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='customer_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='scheduled_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_appointments', to='service_rest.technician'),
        ),
    ]
