# Generated by Django 4.0.3 on 2022-10-25 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0008_alter_serviceappointment_vin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceappointment',
            old_name='scheduled_time',
            new_name='time',
        ),
    ]
