# Generated by Django 4.0.3 on 2022-10-25 01:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0009_rename_scheduled_time_serviceappointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceappointment',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
