# Generated by Django 4.0.3 on 2022-10-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0010_alter_serviceappointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceappointment',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
