# Generated by Django 4.0.3 on 2022-10-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0012_automobilevo'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappointment',
            name='VIP_treatment',
            field=models.BooleanField(default=False),
        ),
    ]
