# Generated by Django 4.0.3 on 2022-10-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0013_serviceappointment_vip_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappointment',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
